### ISSUE TITLE
Github action - Gitlab CI/CD component?

### ISSUE THREAD

**Issue by gardar** [docsible/docsible#31]
It would be super helpful if there was a published Github action and a Gitlab CI/CD component for docsible or examples on how to use docsible in a Github workflow and a Gitlab CI/CD pipeline.

**Comment by exaluc** [comment]
hello @gardar 
[Github actions](https://raw.githubusercontent.com/docsible/thermo-core/refs/heads/main/.github/workflows/generate-docs.yml)

Gitlab WIP.

**Comment by exaluc** [comment]
[Gitlab CI](https://github.com/docsible/thermo-core/blob/main/.gitlab-ci.yml)

I've create: https://github.com/docsible/devops for a late documentation on this. You'r welcome if you want to contribute
