### ISSUE TITLE
[BUG] comment are not included in README.md

### ISSUE THREAD

**Issue by thel0** [docsible/docsible#32]
Problem:

Comment line (task) are not included in README.md

## Environment

- **Docsible Version**: 0.7.0
- **Python Version**: 3.11.2
- **Operating System**:  Linux
## To Reproduce

I have a role analyze with 1 task file
````
$ cat analyze/tasks/postcheck.yml
---
# Get stat of log file
- name: postcheck | Get stats of file log
  ansible.builtin.stat:
      path: report.txt
  register: reportfile

# Test if the size of log file is equal 0
- name: postcheck | Fail if reportfile is 0
  ansible.builtin.fail:
      msg: "ERROR: reportfile is 0"
  when: reportfile.stat.size == 0
````

## Command line:
`$ docsible   -r analyze   --comments`

README.md file is create but comment column are empty

`#### File: tasks/postcheck.yml`

| Name | Module | Has Conditions | Comments |
| ---- | ------ | --------- |  -------- |
| postcheck \| Get stats of file log | ansible.builtin.stat | False |  |
| postcheck \| Fail if reportfile is 0 | ansible.builtin.fail | True |  |
`

**Comment by exaluc** [comment]
Hello @thel0,

Thank you for reporting the issue - I appreciate your attention to detail!
It turns out the `|` character in the playbook task title is causing unexpected behavior due to how titles are processed in the system.

For now, could you please replace `|` with a dash `-` in your task titles? I’ll be working on a solution to handle this character properly soon.

Thanks again for your help!

**Comment by thel0** [comment]
thanks, it's work with '-' character.
I use '|' in task name because "name[prefix]" option is enabled in ansible-lint  [https://ansible.readthedocs.io/projects/lint/rules/name/#nameprefix](url)

**Comment by exaluc** [comment]
Ok, I see.
Working on this.

**Comment by exaluc** [comment]
@thel0 
try this: pip install git+https://github.com/docsible/docsible.git@name-prefix-in-ansible-lint
I'll mr latter if it's ok

**Comment by thel0** [comment]
Thanks, it work :)
```
#### File: tasks/postcheck.yml

                 NAME              │        MODULE        │ HAS CONDITIONS │            COMMENTS
  ─────────────────────────────────┼──────────────────────┼────────────────┼─────────────────────────────────
    postcheck - Get stats of file  │ ansible.builtin.stat │ False          │ Get stat of log file
    log                            │                      │                │
    postcheck - Fail if reportfile │ ansible.builtin.fail │ True           │ Test if the size of log file
    is 0                           │                      │                │ is equal 0`
