### ISSUE TITLE
[BUG] Reading all comments above task

### ISSUE THREAD

**Issue by ddday999** [docsible/docsible#42]
## Describe the Bug

Docsible reading all comments above task, instead of one higher

## Environment

- **Docsible Version**: 0.7.5

## To Reproduce

Write few comments above task ansible.

## Expected Behavior

Read only one string with comment above task. Its important, because much users using ansible-linter, which configuring with help of comments in first lines. When its using in CI/CD, this comments adding in document and ruins description.

Like this:
![image](https://github.com/user-attachments/assets/13c6fd65-531c-4af5-88c7-df5d7062e69c)

Doc:
![image](https://github.com/user-attachments/assets/2098ca06-3fcd-41f6-805f-8fbeae60d82b)

Its shouldn`t be a part of doc

**Comment by ioluc** [comment]
Hello @ddday999 
Sorry for the late reply.
This issue is already resolved on version docsible/0.7.7
```bash
pip install --upgrade docsible
```
