### ISSUE TITLE
Graph condition display

### ISSUE THREAD

**Issue by ddday999** [docsible/docsible#44]
**Is your feature request related to a problem? Please describe.**
Occured problem in graph, that conditions shows in parsed format, like this:
![image](https://github.com/user-attachments/assets/d6c20593-0875-4be3-a172-4bcec55b5a03)

This format is not easy to understand

**Describe the solution you'd like**
Just show "when" in graph same as in ansible code

**Comment by ioluc** [comment]
Hello @ddday999 
This is related to: #30 

Before github update mermaid there where a nice loop like who told it's a when condition.

I would like to integrate the the real condition as it is on task, but sanitize operators while the return is made on jinja2 tpl with a table on markdown, it's start to be hard to find a nice way to implement this without break the readme.

Here is an example of when condition, it's dont look like before. 
[mermaid break on github](https://github.com/docsible/docsible/blob/main/examples/README_demo2.md)

**Comment by gni** [comment]
I'll close this issue since I cannot find a better way to show this with mermaid.
Maybe future version of mermaid will allow me to do a better visual.
